version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: supchaissac
      POSTGRES_PASSWORD: supchaissac_dev
      POSTGRES_DB: supchaissac
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
